### ISSUE TITLE
No Connection Info/Not Saving

### ISSUE THREAD

**Issue by Cimplex** [sbussetti/deluge-siphon#46]
Hey, I've used Siphon before, but unlucky me, I stopped using it for a while and just tried it again today.

Looks like the Options page is bugging out. I can see the events on the checkboxes are working (aka, its calling "save_options()", reset is calling "clear_options()"). Going deeper, I could not actually figure out why the options are not saving.

The text boxes under "Connection Info" are not being populated.

Someone on the Chrome Extension comments edited his comment about an hour ago saying he was getting a weird error that you got resolved before.

Let me know if there is any way I can give you more information about the issue! Sorry if you are already aware/working on this. Thanks.

**Comment by softgripper** [comment]
I'm getting this too.

I keep getting a notification to change delugesiphon on the options page, but it's not saving any info, and it's not grabbing any of my magnetic links unless I right click them.

This has only been occurring since the last update. 0.71.1

**Comment by sbussetti** [comment]
Roger that. On it.

~ Steve

From: softgripper <notifications@github.com> <notifications@github.com>
Reply: sbussetti/deluge-siphon
<reply@reply.github.com>
<reply@reply.github.com>
Date: March 13, 2017 at 5:17:32 AM
To: sbussetti/deluge-siphon <deluge-siphon@noreply.github.com>
<deluge-siphon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [sbussetti/deluge-siphon] No Connection Info/Not Saving (#46)

I'm getting this too.

**Comment by Churchill92** [comment]
Tagging this so I can watch for the update. I had to disable the extension from the constant spamming of the extension.   Also where did the option to add your own remote server go? I don't see an option to link to my server any longer.

**Comment by sbussetti** [comment]
Yeah i'll have an update a little later today. This wasn't happening on my
debug setup but i totally see the problem.

~ Steve

From: Churchill92 <notifications@github.com> <notifications@github.com>
Reply: sbussetti/deluge-siphon
<reply@reply.github.com>
<reply@reply.github.com>
Date: March 13, 2017 at 9:19:46 AM
To: sbussetti/deluge-siphon <deluge-siphon@noreply.github.com>
<deluge-siphon@noreply.github.com>
CC: Steve Bussetti <steve.bussetti@gmail.com> <steve.bussetti@gmail.com>,
Comment <comment@noreply.github.com> <comment@noreply.github.com>
Subject:  Re: [sbussetti/deluge-siphon] No Connection Info/Not Saving (#46)

Tagging this so I can watch for the update. I had to disable the extension

**Comment by drgroot** [comment]
I can confirm this, the connection information boxes do not even appear.

**Comment by silaha** [comment]
I am getting this and found this link on a json header change in 1.3.14 on the Deluge support forum. I suspect it could be related because other Chrome extensions are not working (Darknet).

Here is the [link](http://forum.deluge-torrent.org/viewtopic.php?f=7&t=54428)

**Comment by sbussetti** [comment]
0.71.3 should fix the error on the options page.  @silaha -- thanks for the link although that issue is not related to this error.

**Comment by softgripper** [comment]
Well, I'll try it when chrome can update it. :\

**Comment by softgripper** [comment]
It's still broken.

Not saving details, and not allowing to put in server stuff.

See http://imgur.com/ccc9T4P

I've started using Remote Deluge.  Works great.

**Comment by Churchill92** [comment]
Same Problem as before with the same picture as @softgripper . 

I have no URL link to put in a remote server. I have no Save preferences option. I have no "Web UI" option that appears at all.  It's as if the ability to connect to a remote server is disabled.

**Comment by sbussetti** [comment]
Just pushed version 0.71.4 which should help with even more cases.  Let me know if anyone is still having trouble and I'll keep digging.

**Comment by softgripper** [comment]
So it doesn't save if there is no info in the server section.  Not a huge deal.

Glad you got it at least working.

**Comment by silaha** [comment]
Working for me now on 0.71.4, thank you very much

**Comment by sbussetti** [comment]
@softgripper  yeah -- once you're on the options page, it treats the server url as a required field and won't save without it.  Is there a reason why you'd wanna save settings with no server url set?

**Comment by softgripper** [comment]
No real reason - just I went to try to save it by putting in some check boxes, and didn't get any "required field" text when I hit save.  Seems to work now.

Doesn't really make sense to have it as required - I mean, if you want to just save your check boxes... you can just put rubbish in the URL.  When my deluge server changes IP, or is down for maintenance, I like clearing the stuff out.

Sure, the app won't work without a server, but it wont work with an invalid one either and this is allowed :).  Good old "asdfasdf" server.

Thanks for fixing the plugin.  It's good now.

**Comment by sbussetti** [comment]
@softgripper thanks for feedback.  there's room for improvement for the validation on the options page.  I'll keep it in mind while I'm finishing support for "multiple servers" re: #23

**Comment by Cimplex** [comment]
Nice! Working for me now. Thanks!
